pipeline{
	agent any;
	stages{
		stage('SCM Checkout'){
			steps{
				git branch: 'main', credentialsId: 'medal-cred', url: 'https://github.com/MedalMan/NewRepo'
			}

		}
		stage('Build Docker Image'){
			steps{
				sh 'docker build -t MedalmMan/node-app:latest .';
			}
		}
		stage('Push Docker Image'){
			steps{
			    sh 'docker push MedalMan/node-app:latest';
			}

		}
	}
}
